### ISSUE TITLE
Creating new View on brand new bucket fails

### ISSUE THREAD

**Issue by rajeshetty** [couchbase/couchbase-jvm-core#3]
I'm on Mac OSX Yosetmite, Couchbase 3.0 . 
When I'm creating a new view for an bucket (which is empty at this point). I see following errors

Lost connection to server at 127.0.0.1:8091. Repeating in 2 seconds.  
Repeating failed XHR request.

and when i look at following log files i see more errors.

> views.log   

[views:debug,2015-01-25T16:09:52.079,ns_1@127.0.0.1:capi_set_view_manager-tsky-events<0.4633.0>:capi_set_view_manager:maybe_define_group:381]
Calling couch_set_view:define_group(mapreduce_view, <<"app-events">>, <<"_design/dev_events">>, [{set_view_params,64,[],[],false}])

where as app-events :  is a bucket on which I'm trying to create a view.

> error.log

[ns_server:error,2015-01-25T16:09:22.033,ns_1@127.0.0.1:<0.3493.0>:menelaus_web:loop:170]Server error during processing: ["web request failed",
                                 {path,
                                  "/pools/default/buckets/app-events/ddocs"},
                                 {type,exit},
                                 {what,
                                  {{bad_return_value,
                                    {error,
                                     {error,
                                      {dcp_socket_connect_failed,timeout}}}},
                                   {gen_server,call,
                                    ['capi_set_view_manager-app-events',
                                     {foreach_doc,
                                      #Fun<capi_ddoc_replication_srv.2.125277061>},
                                     infinity]}}},
                                 {trace,
                                  [{gen_server,call,3,
                                    [{file,"gen_server.erl"},{line,188}]},
                                   {capi_ddoc_replication_srv,
                                    full_live_ddocs,2,
                                    [{file,
                                      "src/capi_ddoc_replication_srv.erl"},
                                     {line,62}]},
                                   {capi_ddoc_replication_srv,
                                    sorted_full_live_ddocs,1,
                                    [{file,
                                      "src/capi_ddoc_replication_srv.erl"},
                                     {line,76}]},
                                   {menelaus_web_buckets,
                                    do_handle_ddocs_list,3,
                                    [{file,"src/menelaus_web_buckets.erl"},
                                     {line,1253}]},
                                   {request_throttler,do_request,3,
                                    [{file,"src/request_throttler.erl"},
                                     {line,59}]},
                                   {menelaus_web,loop,2,
                                    [{file,"src/menelaus_web.erl"},
                                     {line,149}]},
                                   {mochiweb_http,headers,5,
                                    [{file,
                                      "/Users/buildbot/buildbot_slave/mac-x64-300-builder/build/build/couchdb/src/mochiweb/mochiweb_http.erl"},
                                     {line,94}]},
                                   {proc_lib,init_p_do_apply,3,
                                    [{file,"proc_lib.erl"},{line,239}]}]}]

I'm not sure which forum would address , Since this is couchbase internal dev community thought this might be the right place to ask for help.

>> Update 

I also tried uninstalling whole couchbase and reinstalling and creating brand new bucket and view - same issue. 

-Thanks
Rajesh

**Comment by daschl** [comment]
@rajeshetty are you still seeing the issue with a recent release? (java client 2.1.1 and server 3.0.2?) 

if you still see it, maybe you want to raise it at forums.couchbase.com first and then we can open server/client tickets if it still is there.

**Comment by rajeshetty** [comment]
Yes I'm still seeing this and I have been talking to couchbase support on this and they tried to figure this out but they could not. As of now I'm working thru some alternative by using remote linux box for views (painful but works!).

**Comment by daschl** [comment]
Okay, please funnel this through our support chain then, thanks!

**Comment by janabant** [comment]
I have the same issue with couchbase server 3.0.3 on redhat linux
Bucket goes down when i try to define a view; works fine when i delete and re-add the bucket until i try to add a view again
http://stackoverflow.com/questions/29444601/couchbase-bucket-goes-down-when-defining-a-view

My osx installation works fine

**Comment by daschl** [comment]
@janabant can you file an issue on the server? I don't think this is a client issue.

--> http://www.couchbase.com/issues/browse/MB

also, please run the code so the server is in this state and then you do a `cbcollectinfo` and attach the generated zip to the ticket as well.

**Comment by hookenz** [comment]
I'm getting this issue with couchbase 3.03 well.

**Comment by daschl** [comment]
@hookenz can you file an issue as described above? I don't know if @janabant did :)

**Comment by janabant** [comment]
I did not file an issue
I had to move my setup to a diff host; this issue never happened there

**Comment by hookenz** [comment]
I think my issue might be a bad drive.  So I'm just trying some things out as it's not random, it always occurs on the same instance of couchbase.  I ran a memtest86+ over the weekend and memory is fine.  Drive isn't showing errors but copied files to it caused a machine reset so I'm investigating that first.

**Comment by daschl** [comment]
@hookenz any update?

**Comment by hookenz** [comment]
@daschl - There is an issue filed here:  https://issues.couchbase.com/browse/MB-15114 
In my case, I think it's some sort of docker+couchbase issue.  Traun has been looking at this.

**Comment by simonbasle** [comment]
the issue has been resolved from what I can see today, going to close that issue. Notice that Github issues should have been deactivated on this repository (in favor of [JIRA](http://issues.couchbase.com) like all other SDKs), which will be done after this issue is closed
